#! /bin/bash

echo "Run this only in WSL, if accidentally run under real Linux press Ctrl+C now"

sudo add-apt-repository ppa:far2l-team/ppa -y
sudo apt install far2l

sudo apt install openssh-server
sudo apt install putty-tools

WIN_HOME=`wslpath "$(wslvar USERPROFILE)"`/WSL
FINGERPRINT=`sudo ssh-keygen -l -E md5 -f /etc/ssh/ssh_host_ed25519_key | awk '{print $2}' | cut --delimiter=':' -f 2-`

mkdir -p $WIN_HOME

echo "set password to none by pressing enter twice"
puttygen -t rsa -b 2048 -C "access to wsl" -o $WIN_HOME/wsl_access.ppk -q
puttygen $WIN_HOME/wsl_access.ppk -o $WIN_HOME/wsl_access.pub -O public-openssh
puttygen $WIN_HOME/wsl_access.ppk -o $WIN_HOME/wsl_access.private -O private-openssh

# we only need single key to access WSL from host
cat $WIN_HOME/wsl_access.pub > ~/.ssh/authorized_keys

# set up ssh server in WSL.
# it must use non-22 port, as port 22 can be busy by host's own SSH server
sudo tee /etc/ssh/sshd_config >/dev/null << THE_END
# this file autogenerated by bootstrapping script
Include /etc/ssh/sshd_config.d/*.conf
Port 2211
ListenAddress 0.0.0.0
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
THE_END

cat > $WIN_HOME/ssh_to_wsl.bat << THE_END
@echo off
wsl -u root service ssh start
FOR /F %%I IN ('wsl hostname -I') DO (SET WSL_IP=%%I)
FOR /F %%I IN ('wsl whoami') DO (SET WSL_USER=%%I)
ssh %WSL_USER%@%WSL_IP% -p2211 -i %USERPROFILE%\\WSL\\wsl_access.private
THE_END

cat > $WIN_HOME/far_wsl.bat << THE_END
@echo off
wsl -u root service ssh start
FOR /F %%I IN ('wsl hostname -I') DO (SET WSL_IP=%%I)
FOR /F %%I IN ('wsl whoami') DO (SET WSL_USER=%%I)
%X_SERVER_PATH%\\plink -hostkey $FINGERPRINT -ssh %WSL_USER%@%WSL_IP% -i %USERPROFILE%\\WSL\\wsl_access.ppk -P 2211 -X -batch far2l
THE_END

cat > $WIN_HOME/autorun_xserver.bat << THE_END
@echo off
start /B "Title:x-server" "%X_SERVER_PATH%\\vcxsrv.exe" :0 -multiwindow -ac -listen tcp
THE_END

cat > $WIN_HOME/run_once_in_xserver_dir.bat << THE_END
@echo off
setx X_SERVER_PATH "%CD%"
copy "%USERPROFILE%\\WSL\\autorun_xserver.bat" "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"
THE_END

exit 0